name       : python-packaging
version    : '20.9'
release    : 15
source     :
    - https://pypi.io/packages/source/p/packaging/packaging-20.9.tar.gz : 5b327ac1320dc863dca72f4514ecc086f31186744b84a230374cc1fd776feae5
license    : Apache-2.0
component  : programming.python
summary    : Core utilities for Python packages
description: |
    Core utilities for Python packages
builddeps  :
    - pkgconfig(python3)
    - python-pretend
    - python-pytest
    - python2-pytest
    - python-setuptools
rundeps    :
    - pyparsing
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python3_test py.test3 -v
    %python_test py.test -v
