name       : python-packaging
version    : '21.0'
release    : 13
source     :
    - https://pypi.io/packages/source/p/packaging/packaging-21.0.tar.gz : 7dc96269f53a4ccec5c0670940a4281106dd0bb343f47b7471f779df49c2fbe7
license    : Apache-2.0
component  : programming.python
summary    : Core utilities for Python packages
description: |
    Core utilities for Python packages
builddeps  :
    - pkgconfig(python3)
    - python-pretend
    - python-pytest
    - python2-pytest
    - python-setuptools
rundeps    :
    - pyparsing
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    #python_test py.test -v
    %python3_test py.test3 -v
