name       : python-packaging
version    : '21.3'
release    : 16
source     :
    - https://pypi.io/packages/source/p/packaging/packaging-21.3.tar.gz : dd47c42927d89ab911e606518907cc2d3a1f38bbd026385970643f9c5b8ecfeb
homepage   : https://github.com/pypa/packaging
license    : Apache-2.0
component  : programming.python
summary    : Core utilities for Python packages
description: |
    Reusable core utilities for various Python Packaging interoperability specifications. This library provides utilities that implement the interoperability specifications which have clearly one correct behaviour (eg: PEP 440) or benefit greatly from having a single shared implementation (eg: PEP 425).
builddeps  :
    - pkgconfig(python3)
    - python-pretend
    - python-pytest
rundeps    :
    - pyparsing
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3 -v
