name       : python-packaging
version    : '19.2'
release    : 6
source     :
    - https://files.pythonhosted.org/packages/5a/2f/449ded84226d0e2fda8da9252e5ee7731bdf14cd338f622dfcd9934e0377/packaging-19.2.tar.gz : 28b924174df7a2fa32c1953825ff29c61e2f5e082343165438812f00d3a7fc47
license    : Apache-2.0
component  : programming.python
summary    : Core utilities for Python packages
description: |
    Core utilities for Python packages
builddeps  :
    - pkgconfig(python3)
    - python-pretend
    - python-pytest
    - python-setuptools
rundeps    :
    - pyparsing
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test py.test -v
    %python3_test py.test3 -v
