name       : python-packaging
version    : 18.0
release    : 4
source     :
    - https://files.pythonhosted.org/packages/cf/50/1f10d2626df0aa97ce6b62cf6ebe14f605f4e101234f7748b8da4138a8ed/packaging-18.0.tar.gz : 0886227f54515e592aaa2e5a553332c73962917f2831f1b0f9b9f4380a4b9807
license    : Apache-2.0
component  : programming.python
summary    : Core utilities for Python packages
description: |
    Core utilities for Python packages
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - pyparsing
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
