name       : python-packaging
version    : '20.8'
release    : 9
source     :
    - https://files.pythonhosted.org/packages/d7/c5/e81b9fb8033fe78a2355ea7b1774338e1dca2c9cbd2ee140211a9e6291ab/packaging-20.8.tar.gz : 78598185a7008a470d64526a8059de9aaa449238f280fc9eb6b13ba6c4109093
license    : Apache-2.0
component  : programming.python
summary    : Core utilities for Python packages
description: |
    Core utilities for Python packages
builddeps  :
    - pkgconfig(python3)
    - python-pretend
    - python-pytest
    - python-setuptools
rundeps    :
    - pyparsing
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test py.test -v
    %python3_test py.test3 -v
