name       : python-packaging
version    : '19.0'
release    : 5
source     :
    - https://pypi.org/packages/source/p/packaging/packaging-19.0.tar.gz : 0c98a5d0be38ed775798ece1b9727178c4469d9c3b4ada66e8e6b7849f8732af
license    : Apache-2.0
component  : programming.python
summary    : Core utilities for Python packages
description: |
    Core utilities for Python packages
builddeps  :
    - pkgconfig(python3)
    - python-pretend
    - python-pytest
    - python-setuptools
rundeps    :
    - pyparsing
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test py.test -v
    %python3_test py.test3 -v
